### ISSUE TITLE
Issue viewing dashboard

### ISSUE THREAD

**Issue by lstables** [laravel/vapor-ui#11]
Hi,

I have the following error.

<img width="872" alt="Screenshot 2020-09-03 at 15 08 48" src="https://user-images.githubusercontent.com/1168291/92125995-8e665e80-edf7-11ea-8277-c9cd9016f3f1.png">

I followed the docs, installed and I'm using `Laravel 7.26.0`
Any help/advice greatly appreciated :)

**Comment by nunomaduro** [comment]
The dashboard was meant to be visualized on an AWS runtime.

Therefore, you must do a: `vapor deploy`, and visit the dashboard thought your vanity URL for example.

If you really want to see the dashboard locally, you must follow the docs here: [docs.vapor.build/1.0/resources/logs.html#local-environment](https://docs.vapor.build/1.0/resources/logs.html#local-environment).

**Comment by lstables** [comment]
Thanks Nuno, maybe that can be written in the documentation for the next person perhaps? :)

**Comment by nunomaduro** [comment]
Maybe. Can you propose it here: https://github.com/laravel/vapor-docs?

**Comment by baj84** [comment]
When I try to access this on my staging vanity url I get 503 Forbidden. Would anyone know why?

**Comment by nunomaduro** [comment]
@baj84 Can you reach support about that?
