### ISSUE TITLE
Would it be possible to allow the use of JWT auth

### ISSUE THREAD

**Issue by KieronWiltshire** [laravel/vapor-ui#13]
My application uses JWTs outside of the cookie. Is it possible to use this dashboard with JWTs instead?

**Comment by nunomaduro** [comment]
@KieronWiltshire You would like to override the middleware stack like you would do with Telescope right? https://github.com/laravel/telescope/blob/c57c343a3590a400ca4f57a03428c23f1c0e46c4/config/telescope.php#L69

**Comment by KieronWiltshire** [comment]
I didn’t know that was possible in telescope. Is it possible to use telescope instead of vapor ui? Or is it better to use vapor UI? But yes... something like that would be ideal.

**Comment by nunomaduro** [comment]
@KieronWiltshire The solution for this may be publish a config file on user-land, where the user can customise the middleware stack.

But first, can you make sure that changing this https://github.com/laravel/vapor-ui/blob/668b4cff63087d0ea8ba44555e8097d191cc24fa/routes/web.php#L14 would work for you?

**Comment by KieronWiltshire** [comment]
@nunomaduro well the issue wouldn't necessarily be there, since the requests are coming in from the front-end, there would need to be a method of attaching the JWT to the authorization header.

**Comment by oyed** [comment]
@nunomaduro Would be great to allow the middleware to be customized, or specifically the use of a custom auth driver - for example, `auth.basic:web,username` (Working locally directly modifying routes)

**Comment by nunomaduro** [comment]
@oyed @KieronWiltshire Can any of you work in pull request for this? Otherwise I will.

The idea is be able to publish a config file just like horizon: https://github.com/laravel/horizon/blob/48229555075d3f46d782d77794705c60c9c7b379/config/horizon.php#L73.

**Comment by KieronWiltshire** [comment]
@nunomaduro i probably could, but not any time soon.

**Comment by KieronWiltshire** [comment]
@nunomaduro there is a slight issue with this though... it assumes that the auth driver is using cookies. What if I want to auth vapor-ui using the Authorization header. It makes no sense to implement this unless the user is using sanctum.

**Comment by ugurgungezerler** [comment]
#22

**Comment by berkansahin** [comment]
> #22

Greate job thanks 👍

**Comment by oyed** [comment]
> #22

Lovely! Thanks for taking the time
