### ISSUE TITLE
Default timestamp for logs is wrong

### ISSUE THREAD

**Issue by jcorrego** [laravel/vapor-ui#17]
- Vapor UI Version: 0.0.6
- Laravel Version: 8.2.0
- PHP Version: 7.4.10
- Database Driver & Version: Mysql 8

### Description:
When i load /vapor-ui url, it loads with selected time 5 hours from now, so its in the future and of course doesnt display anything. (The 5 hours difference correspond to my timezone that is UTC-5). 
To make things worst, when i click on Job->Metrics and the back to Logs->HTTP, its now 10 hours in the future. if i repeat that click series, it continues incrementing 5 hours to the logs screen...

My timezone is correctly configured in my application, and has been working fine for many years. Laravel Nova also respects my timezone. I have to manually change the start datetime, but its also a little difficult because it changes back again when it finish loading items...

### Steps To Reproduce:
- Load HTTP Logs Screen
- Click  on Job->Metrics
- Click on Logs->HTTP
- Click  on Job->Metrics
- Click on Logs->HTTP
- ...

**Comment by nunomaduro** [comment]
This is very weird. Normally this package works perfectly with any timezone.

Can you try to reproduce and identify the bug yourself? Do you need help to setup things locally?

**Comment by jcorrego** [comment]
> This is very weird. Normally this package works perfectly with any timezone.
> 
> Can you try to reproduce and identify the bug yourself? Do you need help to setup things locally?

Yes, how can i debug/compile the package to be able to identify the issue... thanks for your help.

**Comment by nunomaduro** [comment]
Thank you! Can't wait to understand what the issue was. 🙂

**Comment by jcorrego** [comment]
#18 I get it working by removing the timezone setting statements from `app.js` and `Search.vue` component. moment.js automatically loads with the correct timezone, so no need for that.  I think this need more testing, i did a clean laravel installation and worked fine, using my timezone UTC-5. @nunomaduro

**Comment by nunomaduro** [comment]
Thanks for contributing. This issue has been addressed: https://github.com/laravel/vapor-ui/commit/3d7d269aa985e92480f0999ff4b91aff190926e0.

The release `v0.0.8` contains this fixed.
