### ISSUE TITLE
Job metrics for environments with multiple queues

### ISSUE THREAD

**Issue by heathyboyj** [laravel/vapor-ui#24]
Hi,

I've just got the vapor-ui setup in my application over the weekend, but noticed that the metrics for jobs are only reporting from the default queue for the Vapor environment. It'd be great to be able to see the metrics and failed jobs for each once our migration to Vapor is complete, as our existing production environment runs on multiple queues using Redis with Horizon.

Is this something that would be feasible to add to the vapor-ui? And if so, is it already on the vapor-ui team's roadmap, or would this be something that only comes in if developed via an external pull request?

Thanks!

**Comment by nunomaduro** [comment]
I think we would be open for an external pull request on this. Do you have an idea on how you would implement this?

**Comment by heathyboyj** [comment]
Thanks for the response. 

I've not given much thought to the specifics of it or had a look at the underlying code at all. The most important thing for us would be the ability to spot a backlog of jobs in a given queue, but I suppose in an ideal world we'd want to be able to see all the job metrics either broken down to an individual queue or totalled for the entire application.

If someone else doesn't beat me to it, I imagine I'll take a look at it it properly once the migration of our application to Vapor is complete!

**Comment by nunomaduro** [comment]
No plans to implement this myself for this next couple weeks.
