### ISSUE TITLE
Don't load all failed jobs

### ISSUE THREAD

**Issue by georgeboot** [laravel/vapor-ui#25]
Currently the "jobs" page will load all failed jobs from the database, in order to calculate the statistics.

We had quite a bit of failed jobs in our database (~500.000) which obviously took too long to load. This resulted in the request timing out and the statistics not loading.

Code: https://github.com/laravel/vapor-ui/blob/e95c9a7098ca27d6cd0b8655af12ce649fa1a14e/src/Repositories/JobsMetricsRepository.php#L223

I'm not sure what the proper solution to this issue would be. Ideally, we would run one query that gives us all the statistics we need (that we now calculate using the collections).

Thoughts? Willing to contribute on a fix but not sure about what's desired here.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by adrianb93** [comment]
I experienced this. Had 100,000 failed jobs and the metrics and failed jobs pages failed to load.
