### ISSUE TITLE
Feature request: insights into overprovisioned memory

### ISSUE THREAD

**Issue by georgeboot** [laravel/vapor-ui#27]
It would be amazing if this package could give users some insights into their actual lambda memory usage versus the configured memory limit. This could help users find a more optimised memory setting. 

Running the following query in CloudWatch Insights on a lambda http log:
```
filter @type = "REPORT"
| stats max(@memorySize / 1024 / 1024) as provisonedMemoryMB,
  min(@maxMemoryUsed / 1024 / 1024) as smallestMemoryRequestMB,
  avg(@maxMemoryUsed / 1024 / 1024) as avgMemoryUsedMB,
  max(@maxMemoryUsed / 1024 / 1024) as maxMemoryUsedMB,
  provisonedMemoryMB - maxMemoryUsedMB as overProvisionedMB
```

results in:
| provisonedMemoryMB | smallestMemoryRequestMB | avgMemoryUsedMB | maxMemoryUsedMB | overProvisionedMB |
|--------------------|-------------------------|-----------------|-----------------|-------------------|
| 732.4219           | 232.6965                | 309.3292        | 311.8515        | 420.5704          |

**Comment by nunomaduro** [comment]
Those stats are available for every customer at the moment? Without activating any option?

**Comment by georgeboot** [comment]
yes they are. These use the existing, by default activated, lambda logs

**Comment by fgilio** [comment]
I'd be great to have this insight available for HTTP, CLI and Queue Lambdas.
I'd bet in most apps there is a substantial difference between those 3, at least in our apps there is.

**Comment by aaronhuisinga** [comment]
This would be very, very helpful. It's something that I spent a lot of time in the beginning working on, that really isn't easy to figure out until you spend time figuring it out. Codebases change over time as well, and having something in the dashboard to reference versus needing to check it out manually would be a huge improvement.

**Comment by nunomaduro** [comment]
Gonna close this issue, but we are open for a pull request that adds this feature. 👍🏻
