### ISSUE TITLE
Feature request: log slow requests

### ISSUE THREAD

**Issue by georgeboot** [laravel/vapor-ui#28]
For most people, the AWS Console with all it's tools is quite a bit of a black box.

Since you pay for each 100ms your lambda function runs, it is beneficial to fix slow request. However, finding these request is currently quite hard.

If you enable request logs on your API Gateway, you can query them using CloudWatch Insigts. We do so and use it to show our top-10 slowest request paths:

| # | Avg duration | Method | Path               |
|---|--------------|--------|--------------------|
| 1 | 5000 ms      | GET    | /some/slow-path    |
| 2 | 4900 ms      | POST   | /another/one       |
| 3 | 4800 ms      | POST   | /another/one/again |

For reference:

Insights query
```
fields @timestamp as time, integrationLatency as latency, httpMethod as method, path as url
| filter (integrationLatency>4500)
| sort latency desc
| limit 20
```

API Gateway log format
```json
{
    "requestId": "$context.requestId",
    "httpMethod": "$context.httpMethod",
    "status": "$context.status",
    "path": "$context.path",
    "responseLatency": "$context.responseLatency",
    "integrationLatency": "$context.integrationLatency"
}
```

**Comment by nunomaduro** [comment]
This is a great proposal. Do you mind pull requesting a "tab" requests with this information?

**Comment by nunomaduro** [comment]
Gonna close this issue, but can't wait to see a pull request on this. 👍
