### ISSUE TITLE
The Vapor UI assets are not published - on production

### ISSUE THREAD

**Issue by bradley-r-martin-pt** [laravel/vapor-ui#32]
- Vapor UI Version: 0.0.11
- Laravel Version: 7.28.4

Hey Guys,
i am receiving the following issue when trying to access vapor ui. I imagine that it has something to do with the public folder files being deleted and uploaded to cloudflare. 

The Vapor UI assets are not published. Please run: `php artisan vapor-ui:install.

Any suggestions to resolve this ?

**Comment by nunomaduro** [comment]
Please run `php artisan vapor-ui:install` locally before running `vapor deploy`.

**Comment by Casmo** [comment]
For those coming from Google and still running in this error. I added the `@php artisan vapor-ui:publish --ansi` in the `post-autoload-dump` tag of `composer.json` which resolved it for me:

```json
"post-autoload-dump": [
    "@php artisan vapor-ui:publish --ansi"
],
```
