### ISSUE TITLE
Not getting any logs despite seeing them in Vapor dashboard

### ISSUE THREAD

**Issue by kchoppin** [laravel/vapor-ui#36]
- Vapor UI Version: 1.0
- Laravel Version: 7.28
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
After installing and configuring Vapor UI, I can see the metrics and failed jobs fine, but cannot see any logs for http, cli or queue no matter what or how far back I search I always get "No entries were found for the given search criteria. ". I also do not get an option to "keep searching" as mentioned in other issues. If I login to the Vapor website I can see recent logs no problem.

### Steps To Reproduce:
1. Fresh install of Vapor UI using: composer require laravel/vapor-ui
2. Publish assets using: php artisan vapor-ui:install
3. Add VAPOR_ENVIRONMENT & VAPOR_PROJECT to .env for staging environment
4. Try to access logs on http://localhost/vapor-ui

**Comment by nunomaduro** [comment]
After running `php artisan vapor-ui:install`, you should:

1. Configure the "Dashboard Authorization": [docs.vapor.build/1.0/introduction.html#installing-the-vapor-ui-dashboard](https://docs.vapor.build/1.0/introduction.html#installing-the-vapor-ui-dashboard).
2. Deploy your application, and see your logs using the vanity url: https://your-vanity-url.vapor.com/vapor-ui.

**Comment by kchoppin** [comment]
I was under the impression vapor ui could be run from local development to see online environments. Is this not the case?

**Comment by kchoppin** [comment]
@nunomaduro It says here we can use view our online logs locally. https://docs.vapor.build/1.0/resources/logs.html#visualizing-logs
