### ISSUE TITLE
Logs are no longer being displayed after placing the lambdas into a custom VPC

### ISSUE THREAD

**Issue by maegnes** [laravel/vapor-ui#41]
- Vapor UI Version: 1.0.0
- Laravel Version: 8.19.0
- PHP Version: 7.4
- Database Driver & Version: RDS MySQL 8.0

### Description:
As we needed a fixed outgoing IP address for our lambda containers (firewall whitelisting) we placed them into a custom VPC. We followed the official vapor documentation (https://docs.vapor.build/1.0/projects/environments.html#gateway-versions). Everything works like a charm. But if I want to view the logs in vapor-ui (HTTP, CLI and Queue) they are empty and cannot be retrieved. Always getting the message below

![Bildschirmfoto 2020-12-17 um 16 19 58](https://user-images.githubusercontent.com/5019381/102506785-c5e5d780-4083-11eb-9af6-8d72948169b1.png)

### Steps To Reproduce:

1. Place your vapor lambdas into a VPC according official vapor documentation
2. Open /vapor-ui in your browser
3. Try to check the logs

**Comment by nunomaduro** [comment]
@maegnes Interesting. If you click on "click here to keep searching" what happens?

**Comment by maegnes** [comment]
@nunomaduro after clicking "click here to keep searching" it still remains empty (for HTTP and Queue - for CLI i can see the correct log entries). I can see that the "entries" node in the ajax response is completely empty for HTTP and Queue.

I'm testing on two separate environments. The only difference is the VPC configuration in the vapor.yml settings. Without the VPC settings everything works perfectly. Very strange... Dou you have an idea?

**Comment by nunomaduro** [comment]
@maegnes I may need some extra information about your environment to better troubleshoot this. Please reach out our support at **vapor@laravel.com**.
