### ISSUE TITLE
No Support for Composer 2.0

### ISSUE THREAD

**Issue by designbyjr** [laravel/vapor-ui#43]
- Vapor UI Version: 1.11
- PHP Version: 7.4.12
### Description:
hirak/prestissimo Fails as a dependency and is not needed in composer 2.0. See hirak/prestissimo support for 2.0 and you will see the suggestion is to remove it as a dependency in composer 2.0 because there is no need for it.

### Steps To Reproduce:
Just try to install it.

**Comment by nunomaduro** [comment]
This does not seem a Vapor UI issue, as we don't use "hirak/prestissimo".
