### ISSUE TITLE
Feature request: Be able to add other queues to be monitored

### ISSUE THREAD

**Issue by GustavoEdny** [laravel/vapor-ui#45]
Hi there. 

Currently it's not possible to monitor  queued jobs on other queues than the default in the vapor-ui dashboard. 

What I propose is a way to add a list of custom queues on the vapor-ui config file. So this way we can keep track of all the jobs per queue. To be honest I'm not sure about the current implementation and if it's easy to implement. But it could help a lot I think.

**Comment by nunomaduro** [comment]
Please see: https://github.com/laravel/vapor-ui/issues/24. Any reason why you are using multiple queues?

**Comment by GustavoEdny** [comment]
Hi guys. Sorry for the delay.

@nunomaduro The reason to use multiple queues is that we are trying to process live data, our software needs process live data from a lot of sports events and the number of that events being processed could vary depending on the day of the week or even the hour. 

It's also a long running task so we don't want that any of these jobs wait to be processed, so our initial strategy is to have a queue for each sport.

It could be very helpful for us to keep track of these jobs. Let me know what do you think, I think I can help on this implementation.
