### ISSUE TITLE
Two entries for single Log::debug causing json_decode syntax error

### ISSUE THREAD

**Issue by awebartisan** [laravel/vapor-ui#47]
- Vapor UI Version: 1.0.3
- Laravel Version: 8.38.0
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 8

### Description:
Manually doing a `Log::debug()` with custom array data causes the `event message` to be split into two entries.

`Log::debug('rateprovidertest.myshopify.com', ['payload' => $payloadArray]);`

This above line should only display `rateprovidertest.myshopify.com` in the table and the payload should go in `context` object. But this JSON is not decoded at all. `json_last_error_message()` gives a `Syntax Error` too.
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/29105478/116382772-b3e52400-a82f-11eb-937c-cdc55297cc67.png">

### Steps To Reproduce:
`Log::debug()` something like [example json data](https://pastebin.com/nqmADL29) in your project hosted on Laravel Vapor and then try to see this log in Vapor UI.

### Thoughts:
I am not sure if this is a problem on Laravel Vapor side or AWS side. Why one `Log::debug()` is split into **two** events?

**Comment by nunomaduro** [comment]
@awebartisan What happens if you use a small array entry?

**Comment by awebartisan** [comment]
Search view:
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/29105478/116485150-f34d5800-a8a3-11eb-9d9a-14703be69829.png">

Detail view:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/29105478/116485212-12e48080-a8a4-11eb-9fe8-17112af4b24f.png">

As we can see with small piece of data, it works as expected and context data is properly formatted.

**Comment by nunomaduro** [comment]
@awebartisan I am afraid this issue happens because the "Event size" aka line size in CloudWatch can not exceed 256 KB. Therefore, the default behavior in CloudWatch is to split the log event into multiple lines. Can you please verify this information?

In addition, do you have any proposal about how we should address this issue?

**Comment by nunomaduro** [comment]
Well, we simply configure those environment variables by default on Environments deployed by Vapor:

```
'LOG_CHANNEL' => 'stderr',
'LOG_STDERR_FORMATTER' => 'Laravel\Vapor\Logging\JsonFormatter',
```

Meaning that outputting to `stderr` makes logs appearing in CloudWatch.

**Comment by fourstacks** [comment]
Presumably there's some kind of API call going out to AWS somewhere in the stack though right?

I'm not familiar with `stderr` as a log channel.  I get that `JsonFormatter` is used to wrap the logged data before it's processed by (I presume) Monolog.  It's the bit between monolog and AWS that I'm fuzzy on - at some point a logged piece of data has to be sent to Cloudwatch?

**Comment by nunomaduro** [comment]
@fourstacks When using Lambda functions, anything you write to `stdout` or `stderr` becomes a new line in your CloudWatch logs. AWS will add some info like the date and time, the request ID, and the log level.

At this time, we don't have plans to change this on Vapor runtime itself. Any change would have to be done on the this package specifically, like merge two records on the "https://github.com/laravel/vapor-ui/blob/master/src/Repositories/LogsRepository.php", etc.

**Comment by didix16** [comment]
Hello there.
I know this is closed but I'm facing a similar issue and I don't find a solution.... 
On my CloudWatch amb facing that a log has been splited in several fragments, in a particular case, 3 fragments! If I collect the whole json (i.e: message, context, level, level_name, channel, datetime and extra) the amount bytes are 2925 and Amazon splited them like this: the first one into 1023, the second into 1023 and the last one into 879.

So like the AWS documentation says, the maximum value of event size is 256K! Why is splitting almost 3K into 3 fragments. It does no have sense and for me is impossible to debug my logs...

Any idea why is this happening? Is there any kind of special logic that splits the logs into 1023 o 1024 bytes chunk,
Is there anything you have to config to change that behaviour? I mean, is something that I have to change in AWS or is something I have to change in Vapor?

Thanks in advance
