### ISSUE TITLE
Laravel Vapor UI without session

### ISSUE THREAD

**Issue by tasarsu** [laravel/vapor-ui#53]
Hi there, I have an api which I don't have sessions. We used token based auth. 
Is it possible to have vapor-ui with out session?

if it is used only for auth guard maybe we can have an ip restriction instead of user.

When I try to open vapor-ui dashboard I got this error. 

```
{
  "message": "Target class [session] does not exist. (View: /var/task/vendor/laravel/vapor-ui/resources/views/layout.blade.php)",
  "context": {
    "view": {
      "view": "/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php",
      "data": []
    },
    "exception": {
      "class": "Facade\\Ignition\\Exceptions\\ViewException",
      "message": "Target class [session] does not exist. (View: /var/task/vendor/laravel/vapor-ui/resources/views/layout.blade.php)",
      "code": 0,
      "file": "/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:838",
      "previous": {
        "class": "Illuminate\\Contracts\\Container\\BindingResolutionException",
        "message": "Target class [session] does not exist.",
        "code": 0,
        "file": "/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:838",
        "previous": {
          "class": "ReflectionException",
          "message": "Class \"session\" does not exist",
          "code": -1,
          "file": "/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:836"
        }
      }
    }
  }
}
```

kind regards.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
