### ISSUE TITLE
Can't open Logs/Show in new tab

### ISSUE THREAD

**Issue by duncanmcclean** [laravel/vapor-ui#54]
- Vapor UI Version: 1.0.3
- Laravel Version: 8.45.1
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0

### Description:

We've just been doing some testing and logged lots of stuff in a short period of time. However, when trying to view the logs, I wanted to open all the log items for a certain time in new tabs. However, as the view link (the eye) is a `<button>` and not a `<a>` tag, I can't do that.

https://github.com/laravel/vapor-ui/blob/master/resources/js/screens/logs/index.vue#L88

### Steps To Reproduce:

1. Go to Vapor UI logs (doesn't matter the type)
2. Cmd + Click the eye button - nothing happens

**Comment by driesvints** [comment]
Hey @duncanmcclean. This seems something you can send in a PR for. Feel free to do that 👍
