### ISSUE TITLE
Unreadable error messages from failed jobs

### ISSUE THREAD

**Issue by TimothePearce** [laravel/vapor-ui#59]
- Vapor UI Version: 1.1.2
- Laravel Version: 8.49.0
- PHP Version: 8.0.8
- Database Driver & Version: Mysql 8

### Description:
The jobs error messages are cut off.

<img width="1440" alt="Capture d’écran 2021-07-05 à 14 15 18" src="https://user-images.githubusercontent.com/11693661/124470650-2c221580-dd9c-11eb-92cc-f2b53b25c34e.png">

**Comment by driesvints** [comment]
Please provide a way to reproduce this.
