### ISSUE TITLE
More flexibility in route definitions

### ISSUE THREAD

**Issue by alberthaff** [laravel/vapor-ui#62]
Hi.

I would like to be able to customize middleware, domain and prefix for the vapor-ui routes.

The way it's done in Horizon is very flexible, and i think something similar would be a great addition to this package.
Example: https://github.com/laravel/horizon/blob/5.x/src/HorizonServiceProvider.php#L51-L61

**Comment by driesvints** [comment]
Feel free to try a PR 👍
