### ISSUE TITLE
Long commands are always truncated

### ISSUE THREAD

**Issue by oliworx** [laravel/vapor-ui#64]
- Vapor UI Version: ??
- Laravel Version: 8.x
- PHP Version: 7.x
- Database Driver & Version: MySQL

### Description:
After executing commands via the Vapor GUI, the full command line is not visible, it is simpy truncated at 40 characters or so, even though there is plenty of space on a full HD screen.

To see the full command I have to move the mouse pointer over the truncated command, but it is not possible to copy the command to the clipboard.

### Steps To Reproduce:
 - Run command via GUI like `inspire "It is quality rather than quantity that matters. - Lucius Annaeus Seneca"`
 - have a look on the list of "Recent Commands"
 - have a look on latest "Command Details"

**Comment by driesvints** [comment]
Please fill out the versions and resubmit.
