### ISSUE TITLE
Facing issues with vapor-ui customization

### ISSUE THREAD

**Issue by urmik-zwt** [laravel/vapor-ui#70]
- Vapor UI Version: v1.5.1
- Laravel Version: 8.80.0
- PHP Version: ^8.0

We are integrating vapor-ui in our system. so I need to do some customization in the layout and route.

**Layout Customization:**

 I used vapor-UI authentication based on the nova session so I need to add a link into vapor-ui navigation for directly navigating to nova admin and another link add for the logout nova user without going to nova admin. 

So I exported the vapor-ui layout in my resources vendor folder from the vapor-ui package and added nova admin and logout links to navigation. but now it's properly and does not convert any router link to the anchor tag. and also not getting any vapor-ui vuejs component result you can see in the attached images.

![image](https://user-images.githubusercontent.com/79259238/152346802-9e28493d-0e20-41dc-9b36-aa292a16efcc.png)

![Screenshot at Feb 01 20-35-28](https://user-images.githubusercontent.com/79259238/152346916-31c9f927-14c1-42e0-8e12-740906094715.png)

**Route Customization:**

Also, I made some changes in the vapor-ui route. I have moved the web.php file from the "vendor/laravel/vapor-ui/routes/web.php" to the "public/vendor/vapor-ui/routes/web.php" and removed "name('vapor-ui')" from the below code. 

``` Route::middleware('vapor-ui')
    ->group(function () {
        Route::get('/api/logs/{group}', [LogController::class, 'index']);
        Route::get('/api/logs/{group}/{id}', [LogController::class, 'show']);

        Route::get('/api/jobs/metrics', [JobMetricController::class, 'index']);

        Route::get('/api/jobs/{group}', [JobController::class, 'index']);
        Route::get('/api/jobs/{group}/{id}', [JobController::class, 'show']);

        Route::post('/api/jobs/failed/retry/{id}', [JobController::class, 'retry']);
        Route::post('/api/jobs/failed/forget/{id}', [JobController::class, 'forget']);

        Route::get('/{view?}', HomeController::class)->where('view', '(.*)')->name('vapor-ui');
    }); 
```
Because I have changed vapor-ui config and I have changed the path with the "/" but it does not reflect it always reflects with default "vapor-ui" and all the navigation links created with "vapor-ui" so I need to Replace "vapor-ui" with "/" so that I have made this changes. 

But after the made this change vapor-ui getting the error you can see in the attached Image.

![Screenshot at Feb 03 11-46-18](https://user-images.githubusercontent.com/79259238/152348407-c57332c1-178a-4c35-8b2f-e8d7ffcc38ef.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by urmik-zwt** [comment]
Hi @driesvint,

The first one is my customization for the layout I understand, it's not an issue it's a question. but I think the second one is an issue because if I added path using `VAPOR_UI_PATH` environment as mentioned in doc and `vapor-ui.config`  file then should need to replace vapor-ui path with a newly added path for all the vapor-ui navigation links and server error should also not come. I'm not sure about this my above concern, I would be grateful if you could help me to understand or solve this problem. 

![image](https://user-images.githubusercontent.com/79259238/152353350-70081b22-070f-4732-8194-44c9810c9cd5.png)

Thanks
