### ISSUE TITLE
Server Error When Viewing Jobs Details

### ISSUE THREAD

**Issue by ferrari308guy** [laravel/vapor-ui#72]
- Vapor UI Version: 1.5.2
- Laravel Version: 9.8.1
- PHP Version: 8.0.13
- Database Driver & Version: mySQL

### Description:

When trying to view either the Metrics or Failed section for Jobs on Vapor UI, I receive the attached message. This occurs regardless of what queue I select, and what timeframe I select. This error occurs on my production environment only; the staging environment for the exact same application works as expected.

![Capture](https://user-images.githubusercontent.com/73408997/163848966-5d3abad6-555c-45fa-a549-c796e0ca28dd.PNG)

I have checked the application logs per the suggestion and there are no errors related to why this error might be occurring. I also know based on the fact that I am seeing the results of my jobs (e.g., emails being sent, tasks being completed, etc.) that they are indeed running and executing properly.

I can't find any information in the documentation or on the various Laravel help pages about why this might be occurring, or how to fix it. Can the team provide any insight into what generates this error so that I can more effectively debug?

### Steps To Reproduce:

View the Metrics or Failed page for Jobs.

**Comment by driesvints** [comment]
Heya, for this, please contact Vapor support directly and share your Vapor.yml file with them. Thanks
