### ISSUE TITLE
Cloudflare integration

### ISSUE THREAD

**Issue by NinjaJake86** [laravel/vapor-ui#73]
Hello!

Is there any chance we can get a Cloudflare integration so if we are using Cloudflare for our DNS it can be managed like Vapour manages DNS without Cloudflare? Just like using Cloudflare for all my domains and DNS

Cheers!

**Comment by driesvints** [comment]
Hi @NinjaJake86. Since this is a Vapor specific UI tool, I doubt we'll add support for any other service, sorry.
