### ISSUE TITLE
PhpSpreadsheet: error trying to download a Xlsx file on Vapor

### ISSUE THREAD

**Issue by brunomcpena** [laravel/vapor-ui#79]
- Vapor UI Version: 1.5.3
- Vapor Core Version: 2.23.0
- Laravel Version: 8.83.23
- PHP Version: 7.4.30

### Description:

Vapor returns "Internal server error" when I try to download a Xlsx from PhpSpreadsheet. It works locally with Xlsx. It works on Vapor with Csv but not with Xlsx.

AWS Log:
Fatal error: Uncaught Exception: Error encoding runtime JSON response: Malformed UTF-8 characters, possibly incorrectly encoded in /var/task/vendor/laravel/vapor-core/src/Runtime/NotifiesLambda.php:49

Stack trace:
.0 /var/task/vendor/laravel/vapor-core/src/Runtime/NotifiesLambda.php(19): Laravel\Vapor\Runtime\LambdaRuntime->lambdaRequest('[http://127.0.0](http://127.0.0.0/)....', Array)
.1 /var/task/vendor/laravel/vapor-core/src/Runtime/LambdaRuntime.php(53): Laravel\Vapor\Runtime\LambdaRuntime->notifyLambdaOfResponse('9701efbf-d000-4...', Array)
.2 /var/task/fpmRuntime.php(88): Laravel\Vapor\Runtime\LambdaRuntime->nextInvocation(Object(Closure))
.3 /var/task/runtime.php(36): require('/var/task/fpmRu...')
.4 /opt/bootstrap.php(6): require('/var/task/runti...')

### Steps To Reproduce:

1. Add package phpoffice/phpspreadsheet
2. Code:
```php
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet->setActiveSheetIndex(0)->setCellValue('A1', 'Hello');
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="filename.xlsx"');
$writer->save('php://output');
```
3. Vapor returns "Internal server error"

### Expected behavior

Download the file

**Comment by driesvints** [comment]
Hi @brunomcpena can you contact Vapor support instead? This issue tracker is specifically for this package.
