### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by dvlpr91** [laravel/vapor-ui#88]
- Vapor UI Version: 1.7.2
- Laravel Version: 10.4.1
- PHP Version: 8.2
- Database Driver & Version: mysql serverless v2

### Description:
When I followed the documentation, I got an error.

### Steps To Reproduce:

I just ran the command below.

![image](https://user-images.githubusercontent.com/40349371/226287930-2e3b1a48-a13a-466f-a4ee-b4aeb078b1a6.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dvlpr91** [comment]
It was my mistake.

thank you.
