### ISSUE TITLE
Dynamic number of warm lambdas

### ISSUE THREAD

**Issue by chris-hud** [laravel/vapor-ui#92]
I have large projects running with almost entirely US users. I have very high traffic during business hours, but after 6pm on weekdays, and on weekends, I have almost no traffic. 

It would be valuable if I was able to say:
m-f 6am-6pm: 300 warm functions
m-f 6-10 pm 100 warm functions
m-f 10pm - 6am 50 warm functions
s-s all day 50 warm functions

I would think that this would be useful to a number of clients.

**Comment by driesvints** [comment]
Heya. Please try to contact Vapor support with this suggestion, thanks.
