### ISSUE TITLE
Laravel 11.x support

### ISSUE THREAD

**Issue by liepumartins** [laravel/vapor-ui#98]
It seems that vapor-ui cannot be used with Laravel 11

```
- laravel/vapor-ui[dev-master, v1.7.0, ..., 1.x-dev] require laravel/framework ^8.0|^9.0|^10.0 -> 
found laravel/framework[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev] 
but it conflicts with your root composer.json require (^11.0).
```

Please fix.

**Comment by crynobone** [comment]
![CleanShot 2024-03-25 at 17 28 50](https://github.com/laravel/vapor-ui/assets/172966/142259c9-3c86-41c6-a3ea-b057e037fd47)

This has been explained in the README
